// Code generated by mongery. DO NOT EDIT.
package models

const OrderCollection = "order"
const Order_ID = "_id"
const Order_BuyerName = "buyerName" // 구매자명
const Order_BuyerPhone = "buyerPhone" // 구매자 연락처
const Order_PaymentMethod = "paymentMethod" // 결제 수단
const Order_ReceiverName = "receiverName" // 수취인명
const Order_ReceiverPhone = "receiverPhone" // 수취인 연락처
const Order_ReceiverAddress = "receiverAddress" // 배송주소
const Order_ShippingFee = "shippingFee" // 배송비
const Order_ShippingCompanyCode = "shippingCompanyCode" // 택배사
const Order_ShippingCompanyName = "shippingCompanyName" // 택배사명
const Order_InvoiceNumber = "invoiceNumber" // 운송장 번호
const Order_OrderStatus = "orderStatus" // 주문 상태
const Order_SemiOrder = "semiOrder" // 세미오더 목록
const Order_SemiOrder_ID = "semiOrder._id"
const Order_SemiOrder_BuyerName = "semiOrder.buyerName" // 구매자명
const Order_SemiOrder_BuyerPhone = "semiOrder.buyerPhone" // 구매자 연락처
const Order_SemiOrder_PaymentMethod = "semiOrder.paymentMethod" // 결제 수단
const Order_SemiOrder_ReceiverPhone = "semiOrder.receiverPhone" // 수취인 연락처
const Order_person = "persons" // 사람 목록
const Order_person_ID = "persons._id"
const Order_person_Name = "persons.name" // 이름

const ItemOrderCollection = "item_order"
const ItemOrder_ID = "_id"
const ItemOrder_OrderID = "orderID" // 주문 ID
const ItemOrder_ItemID = "itemID" // 상품 번호

type ItemOrders []ItemOrder

func (t ItemOrders) Len() int {
	return len(t)
}

func (t ItemOrders) Append(v ItemOrder) ItemOrders {
	t = append(t, v)
	return t
}

func (t ItemOrders) Empty() bool {
	return len(t) == 0
}

func (t ItemOrders) First() ItemOrder {
	if len(t) == 0 {
		return ItemOrder{}
	}
	return t[0]
}

func (t ItemOrders) Last() ItemOrder {
	if len(t) == 0 {
		return ItemOrder{}
	}
	return t[len(s)-1]
}

