// Code generated by mongery. DO NOT EDIT.
package semiorder

const SemiOrder_ID = "_id"
const SemiOrder_BuyerName = "buyerName"
const SemiOrder_BuyerPhone = "buyerPhone"
const SemiOrder_PaymentMethod = "paymentMethod"
const SemiOrder_ReceiverPhone = "receiverPhone"

