// Code generated by mongery. DO NOT EDIT.
package semiorder

const SemiOrderCollection = "asdf.foo"
const SemiOrder_ID = "_id"
const SemiOrder_BuyerName = "buyerName" // 구매자명
const SemiOrder_BuyerPhone = "buyerPhone" // 구매자 연락처
const SemiOrder_PaymentMethod = "paymentMethod" // 결제 수단
const SemiOrder_ReceiverPhone = "receiverPhone" // 수취인 연락처

